{% set version = "0.8.1" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: ale
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ale.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

requirements:
  build:
    - cmake>=3.10
    - eigen
  host:
    - pip
    - python
    - nlohmann_json
  run:
    - networkx
    - numpy
    - pvl
    - python
    - python-dateutil
    - scipy >=1.2.0
    - spiceypy >=2.3.0
    - pyyaml

# Add the tests eventually
# test:
#

# about:
#   home:
#   license:
#   license_file:
#   summary: "Abstract Layer of Ephimerides"

# extra:
#   recipe-maintainers:
