{% set version = "0.0" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: ale
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ale.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

# A number of the requirements below will have two instances: one will include a specific version
# pinning, while the other one will not. When building a version of ALE for use specifically within
# ISIS, use the instances with the version pinned. For all other builds, use the unpinned instances.
# (Confirm that every requirement has one and only one instance uncommented.)
#
# ISIS requires pinned versions for these dependencies to avoid conflicts with other dependencies.
# Make sure to always confirm that version numbers in this file and version numbers in the
# meta.yaml file within the ISIS3 repo match for each dependency before building this library
# for use within ISIS, and always upload this special ISIS build with the "isis" tag.
requirements:
  build:
  - cmake>=3.10
  - eigen
  - gsl
  run:
  - eigen
  - gsl
  - networkx
  - numpy
  - openblas
  - python
  - python-dateutil
  - pvl
  - pysis
  - spiceypy

# Add the tests eventually
# test:
#

# about:
#   home:
#   license:
#   license_file:
#   summary: "Abstract Layer of Ephimerides"

# extra:
#   recipe-maintainers:
