{% set version = "0.0" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: ale
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ale.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

# Shotgun strat on requirements until we can narrow them down
requirements:
  build:
  - python
  - cmake>=3.10
  - gsl
  - openblas>=0.3.0
  - eigen
  - spiceypy
  - numpy
  - python-dateutil
  - pvl
  run:
  - python
  - cmake>=3.10
  - gsl
  - openblas>=0.3.0
  - eigen
  - spiceypy
  - numpy
  - python-dateutil
  - pvl

# Add the tests eventually
# test:
#

# about:
#   home: https://developers.google.com/protocol-buffers/
#   license: BSD 3-Clause
#   license_file: LICENSE
#   summary: "Protocol Buffers - Google's data interchange format."

# extra:
#   recipe-maintainers:
