{% set version = "0.8.1" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: ale
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ale.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

requirements:
  build:
  - cmake>=3.10
  - eigen
  - nlohmann_json
  host:
  - nlohmann_json

# Add the tests eventually
# test:
#

# about:
#   home:
#   license:
#   license_file:
#   summary: "Abstract Layer of Ephimerides"

# extra:
#   recipe-maintainers:
