{% set version = "0.8.8" %}
{% set git_branch = "master" %}
{% set build_number = "0" %}

package:
  name: ale
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ale.git'
  git_branch: {{ git_branch }}

build:
  number: {{ build_number }}

requirements:
  build:
    - cmake>=3.15
    - eigen
  host:
    - pip
    - python
    - nlohmann_json
  run:
    - networkx
    - numpy
    - pvl
    - python
    - python-dateutil
    - pytz
    - scipy >=1.4.0
    - spiceypy >=4.0.1
    - pyyaml

test:
  imports:
    - ale
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - test -e $PREFIX/lib/libale${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\ale.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\ale.lib exit 1  # [win]

# about:
#   home:
#   license:
#   license_file:
#   summary: "Abstract Layer of Ephimerides"

# extra:
#   recipe-maintainers:
