name: ale
channels:
  - conda-forge
  - default

dependencies:
  # Deps for docs
  - breathe
  - cmake>=3.12
  - doxygen
  - nlohmann_json
  # Deps for ALE
  - brotli
  - eigen
  - gdal
  - numpy
  - pvl
  - pytz
  - python
  - python-dateutil
  - scipy>=1.4.0,<1.11
  - spiceypy>=6.0.0
  - pyyaml
  - networkx