# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ale.models.base_model_ import Model
from ale import util


class RequestISD(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, label: str=None):  # noqa: E501
        """RequestISD - a model defined in OpenAPI

        :param label: The label of this RequestISD.  # noqa: E501
        :type label: str
        """
        self.openapi_types = {
            'label': str
        }

        self.attribute_map = {
            'label': 'label'
        }

        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'RequestISD':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The request_ISD of this RequestISD.  # noqa: E501
        :rtype: RequestISD
        """
        return util.deserialize_model(dikt, cls)

    @property
    def label(self) -> str:
        """Gets the label of this RequestISD.


        :return: The label of this RequestISD.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this RequestISD.


        :param label: The label of this RequestISD.
        :type label: str
        """

        self._label = label
