from ale.base.base import Driver

spiceql_mission_map = {
    "APOLLO_METRIC" : "apollo", 
    "CHANDRAYAAN-1_M3": "m3",
    "CHANDRAYAAN-1_MRFFR": "mrffr",
    "M3": "m3", 
    "CASSINI_ISS_NAC": "cassini",
    "CASSINI_ISS_WAC": "cassini",
    "CASSINI_VIMS_V" : "cassini",
    "DAWN_FC2_FILTER_1": "fc2",
    "DAWN_FC2_FILTER_2": "fc2",
    "DAWN_FC2_FILTER_3": "fc2",
    "DAWN_FC2_FILTER_4": "fc2",
    "DAWN_FC2_FILTER_5": "fc2",
    "DAWN_FC2_FILTER_6": "fc2",
    "DAWN_FC2_FILTER_7": "fc2",
    "DAWN_FC2_FILTER_8": "fc2",
    "GLL_SSI_PLATFORM": "galileo",
    "HAYABUSA_AMICA": "amica",
    "HAYABUSA_NIRS": "nirs",
    "HAYABUSA2_ONC-W2": "",
    "JUNO_JUNOCAM": "juno",
    "LRO_LROCNACL": "lroc",
    "LRO_LROCNACR": "lroc",
    "LRO_LROCWAC_UV": "lroc",
    "LRO_LROCWAC_VIS": "lroc",
    "LRO_MINIRF": "",
    "M10_VIDICON_A": "m10_vidicon_a",
    "M10_VIDICON_B": "m10_vidicon_b",
    "MSGR_MDIS_WAC": "mdis",
    "MSGR_MDIS_NAC": "mdis",
    "MEX_HRSC_SRC": "src",
    "MEX_HRSC_IR": "hrsc",
    "MGS_MOC_NA": "mgs",
    "MGS_MOC_WA_RED": "mgs",
    "MGS_MOC_WA_BLUE": "mgs",
    "MRO_MARCI_VIS": "marci",
    "MRO_MARCI_UV": "marci",
    "MRO_CTX": "ctx",
    "MRO_HIRISE": "hirise",
    "MRO_CRISM_VNIR": "crism",
    "NEAR EARTH ASTEROID RENDEZVOUS": "",
    "MSL_MASTCAM_RIGHT": "",
    "MSL_MASTCAM_LEFT": "",
    "NH_LORRI": "lorri",
    "NH_RALPH_LEISA": "leisa",
    "NH_MVIC": "mvic_tdi",
    "ISIS_NH_RALPH_MVIC_METHANE": "mvic_framing",
    "THEMIS_IR": "odyssey",
    "THEMIS_VIS": "odyssey",
    "ORX_OCAMS_MAPCAM": "",
    "ORX_OCAMS_POLYCAM": "",
    "ORX_OCAMS_SAMCAM": "",
    "ROS_VIRTIS-M_IR" : "rosetta",
    "LISM_MI-VIS1": "kaguya",
    "LISM_MI-VIS2": "kaguya",
    "LISM_MI-VIS3": "kaguya",
    "LISM_MI-VIS4": "kaguya",
    "LISM_MI-VIS5": "kaguya",
    "LISM_MI-NIR1": "kaguya",
    "LISM_MI-NIR2": "kaguya",
    "LISM_MI-NIR3": "kaguya",
    "LISM_MI-NIR4": "kaguya",
    "LISM_TC1_WDF": "kaguya",
    "LISM_TC1_WTF": "kaguya",
    "LISM_TC1_SDF": "kaguya",
    "LISM_TC1_STF": "kaguya",
    "LISM_TC1_WDN": "kaguya",
    "LISM_TC1_WTN": "kaguya",
    "LISM_TC1_SDN": "kaguya",
    "LISM_TC1_STN": "kaguya",
    "LISM_TC1_WDH": "kaguya",
    "LISM_TC1_WTH": "kaguya",
    "LISM_TC1_SDH": "kaguya",
    "LISM_TC1_STH": "kaguya",
    "LISM_TC1_SSH": "kaguya",
    "LO1_HIGH_RESOLUTION_CAMERA": "",
    "LO2_HIGH_RESOLUTION_CAMERA": "",
    "LO3_HIGH_RESOLUTION_CAMERA": "",
    "LO4_HIGH_RESOLUTION_CAMERA": "",
    "LO5_HIGH_RESOLUTION_CAMERA": "",
    "TGO_CASSIS": "cassis",
    "VIKING ORBITER 1": "viking1",
    "VIKING ORBITER 2": "viking2",
    "VG1_ISSNA": "",
    "VG1_ISSWA": "",
    "VG2_ISSNA": "",
    "VG2_ISSWA": "",
    "VISUAL_IMAGING_SUBSYSTEM_CAMERA_A" : "viking1",
    "VISUAL_IMAGING_SUBSYSTEM_CAMERA_B" : "viking1",
    "ULTRAVIOLET/VISIBLE CAMERA": "uvvis",
    "Near Infrared Camera": "nir",
    "High Resolution Camera": "clementine1",
    "Long Wave Infrared Camera": "clementine1",
    "Visual and Infrared Spectrometer": "vir",
}